# Generated by Django 5.2.6 on 2026-02-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='內部筆記'),
        ),
    ]
