# Generated by Django 5.2.6 on 2026-02-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('interview', '面試邀約'), ('rejection', '感謝函 (婉拒)'), ('offer', '錄取通知'), ('other', '其他 / 客製化')], default='interview', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿 (Draft)'), ('queued', '排程中 (Queued)'), ('sent', '已寄出 (Sent)'), ('failed', '失敗 (Failed)')], default='draft', max_length=20)),
                ('subject', models.CharField(max_length=255, verbose_name='信件主旨')),
                ('body', models.TextField(verbose_name='信件內文')),
                ('custom_intent', models.CharField(blank=True, max_length=255, null=True, verbose_name='客製化意圖')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tasks', to='core.application')),
            ],
        ),
    ]
