# Generated by Django 5.2.6 on 2026-02-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('interview', '面試邀約'), ('rejection', '感謝函 (婉拒)'), ('offer', '錄取通知'), ('other', '預設通用')], max_length=20, unique=True, verbose_name='類型')),
                ('subject_template', models.CharField(max_length=255, verbose_name='預設主旨')),
                ('body_template', models.TextField(verbose_name='預設內文 (支援 {{name}} 變數)')),
            ],
        ),
    ]
